module.exports = [
  {
    name: 'BMW X1 BS6',
    price: '1266.31',
    model: 'a4',
    year: '2021',
    image:
      'https://stimg.cardekho.com/images/carexteriorimages/930x620/BMW/X1/7625/1583398555726/front-left-side-47.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'BMW Z4 M40i',
    price: '12366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://www.weeklyvoice.com/wp-content/uploads/2019/11/IMG_4456.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'BMW X7',
    price: '14366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://imgd.aeplcdn.com/664x374/cw/ec/28286/BMW-X7-Left-Front-Three-Quarter-145764.jpg?wm=0&q=85',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'BMW M8',
    price: '12366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://carsguide-res.cloudinary.com/image/upload/f_auto%2Cfl_lossy%2Cq_auto%2Ct_default/v1/editorial/2020-bmw-m8-competition-justin-hilliard-27.png',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Mercedes-Benz AMG-GT',
    price: '12366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://www.mercedes-benz.com/en/vehicles/passenger-cars/amg-gt/mercedes-amg-gt/_jcr_content/root/slider_0/sliderchilditems/slideritem_0/image/MQ7-0-image-20190114123815/01-mercedes-benz-2019-mercedes-amg-gt-c-190-facelift-diamond-white-metallic-amg-night-package-3400x1440.jpeg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Mercedes-Benz C-Class',
    price: '12366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://www.mercedes-benz.co.in/passengercars/mercedes-benz-cars/models/c-class/saloon-w205/explore/highlights/_jcr_content/contentgallerycontainer/par/contentgallery_bfe4/par/contentgallerytile_d/image.MQ6.8.20190711140009.jpeg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Mercedes-Benz GLX',
    price: '12366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https%3A%2F%2Fcdni.autocarindia.com%2FExtraImages%2F20210120034147_2021_Mercedes_GLC.jpg&h=795&w=1200&c=1',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Mercedes-Benz S-Class',
    price: '12366.31',
    model: 'a4',
    year: '2021',
    image:
      'https://gaadiwaadi.com/wp-content/uploads/2020/09/2021-Mercedes-Benz-S-Class-6.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Jeep Grand Cherokee L',
    price: '121266.31',
    model: 'a4',
    year: '2021',
    image:
      'https://cdni.autocarindia.com/ExtraImages/20210108030033_Jeep_Grand_Cherokee_L_main.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Jeep Grand Cherokee L',
    price: '121266.31',
    model: 'a4',
    year: '2021',
    image:
      'https://cdni.autocarindia.com/ExtraImages/20210108030033_Jeep_Grand_Cherokee_L_main.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Ford Edeavour',
    price: '121266.31',
    model: 'a4',
    year: '2021',
    image:
      'https://cdni.autocarindia.com/ExtraImages/20200225012558_BS6-Ford-Endeavour.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Ford Ecosport',
    price: '154786.31',
    model: 'a4',
    year: '2021',
    image:
      'https://autoportal.com/img/new-cars-gallery/ford/ecosport/desc/ford-ecosport-81be0b0.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
  {
    name: 'Ford Mustang',
    price: '154786.31',
    model: 'a4',
    year: '2021',
    image:
      'https://cnet3.cbsistatic.com/img/3vwkGb5WITg4dttXkrXYps_kyFg=/1240x775/2020/09/30/3bbaa877-fd32-45dc-84c2-2c685adef434/2020-ford-mustang-shelby-gt350-heritage-edition-3.jpg',
    fueltype: 'Pertrol',
    transmissionType: 'Automatic',
    bodyType: 'coupe',
    interior: 'leather',
    seating: '4',
    fueltank: '60',
  },
];
